<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * BiensRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiensRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBiens($Localite = 0, $Type = 0, $budget = 0)
    {
        $dql = "SELECT b FROM Akina\ImmobilierBundle\Entity\Biens b
      Join b.Type t Join b.Localite l WHERE b.etat = 1";
        if ($Localite != 0) {
            $dql .= ' AND l.id = :Localite';
        }
        if ($Type != 0) {
            $dql .= ' AND t.id = :Type';
        }
        if ($budget != 0) {
            $dql .= ' AND b.prix BETWEEN :prixMin AND :prixMax';
        }

        $query = $this->getEntityManager()->createQuery($dql);

        if ($Localite != 0) {
            $query->setParameter('Localite', $Localite);
        }
        if ($Type != 0) {
            $query->setParameter('Type', $Type);
        }
        if ($budget != 0) {
            $query->setParameter('prixMin', $budget - 10000)
                  ->setParameter('prixMax', $budget + 10000);
        }

        return $query->getResult();
    }
}
