<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * ConfessionBiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfessionBiensRepository extends \Doctrine\ORM\EntityRepository
{
}
