<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * ContratProprioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratProprioRepository extends \Doctrine\ORM\EntityRepository
{
}
