<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * ContratPropRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratPropRepository extends \Doctrine\ORM\EntityRepository
{
}
