<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * ImageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBien()
    {
        //  $dql = $this->getEntityManager()->createQueryBuilder();
        $dql = "SELECT b FROM Akina\ImmobilierBundle\Entity\Image b
        Join b.biens t WHERE t.etat = 0";
        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    }
}
