<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReservation()
    {
      //  $dql = $this->getEntityManager()->createQueryBuilder();
        $dql = "SELECT b FROM Akina\ImmobilierBundle\Entity\Reservation b 
        WHERE b.etat = 0";
        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    } 
    public function findBien($Bien)
    {
      //  $dql = $this->getEntityManager()->createQueryBuilder();
      $dql = "SELECT b FROM Akina\ImmobilierBundle\Entity\Reservation b 
    left Join b.Bien l WHERE b.etat = 0";
    if($Bien!=0){
        $dql .= "AND l.id = :id";
     }
     $query = $this->getEntityManager()->createQuery($dql);

     if($Bien != 0){
        $query ->setParameter(
            'id', $Bien);
     }
       
        return $query->getResult();
    } 
}
