<?php

namespace Akina\ImmobilierBundle\Repository;

/**
 * TermeContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermeContratRepository extends \Doctrine\ORM\EntityRepository
{
}
