<?php

namespace Proxies\__CG__\Akina\ImmobilierBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Biens extends \Akina\ImmobilierBundle\Entity\Biens implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'id', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'nomBien', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'etat', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'prix', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'description', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'bienParent', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'Proprietaire', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'Type', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'Localite'];
        }

        return ['__isInitialized__', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'id', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'nomBien', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'etat', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'prix', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'description', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'bienParent', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'Proprietaire', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'Type', '' . "\0" . 'Akina\\ImmobilierBundle\\Entity\\Biens' . "\0" . 'Localite'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Biens $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomBien($nomBien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomBien', [$nomBien]);

        return parent::setNomBien($nomBien);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomBien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomBien', []);

        return parent::getNomBien();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(\Akina\ImmobilierBundle\Entity\TypeBien $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalite(\Akina\ImmobilierBundle\Entity\Localite $localite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalite', [$localite]);

        return parent::setLocalite($localite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalite', []);

        return parent::getLocalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setBienParent(\Akina\ImmobilierBundle\Entity\Biens $bienParent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBienParent', [$bienParent]);

        return parent::setBienParent($bienParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getBienParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBienParent', []);

        return parent::getBienParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setProprietaire(\Akina\ImmobilierBundle\Entity\Proprietaire $proprietaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProprietaire', [$proprietaire]);

        return parent::setProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietaire', []);

        return parent::getProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
